#
#Dependencies
markdown: redcarpet
highlighter: pygments

# Setup
title: Sunnyyoung's
tagline: 'Not a bug, it is a feature.'
description: Sunnyyoung's
url: https://Sunnyyoung.net
github: https://github.com/Sunnyyoung
rss: https://Sunnyyoung.net/atom.xml
paginate: 5

# Url
baseurl: /

# Custom vars
version: 1.0.0
